### ISSUE TITLE
Links inside message

### ISSUE THREAD

**Issue by victorwpbastos** [fnando/messages-app#1]
Is there a way to put links inside a message?

**Comment by fnando** [comment]
You can't link specific words, but you can link the whole banner. If you're using Markdown, just use something like the following:

``` markdown
[![This is the alt description](https://messages-svg.herokuapp.com/success.svg?message=This+is+a+success+message!)](http://example.com)
```

which would be rendered as

[![This is the alt description](https://messages-svg.herokuapp.com/success.svg?message=This+is+a+success+message!)](http://example.com)
